EM.GUI_Chef/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

using EM.DomainServices;
using EM.GUI_Chef.Models.ViewModels;
using EM.Domain;
using System.IO;

using EM.Domain.Chef_Entities;

namespace EM.GUI_Chef.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        private UserManager<IdentityUser> userManager;
        private SignInManager<IdentityUser> signInManager;
        private IChefRepository repository;

        public DashboardController(UserManager<IdentityUser> userMgr,
            SignInManager<IdentityUser> signInMgr, IChefRepository repo)
        {
            repository = repo;
            userManager = userMgr;
            signInManager = signInMgr;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Dishes()
        {
            var user = await userManager.GetUserAsync(HttpContext.User);
            return View(repository
                .Dishes(user.Email)
                .Select(d => new DishViewModel{ Dish = d})
                .ToList()
                );
        }

        public IActionResult CreateDish()
        {
            return View("EditDish", new DishViewModel
            {
                Dish = new Dish()
            });
        }

        public IActionResult EditDish(int dishId)
        {
            DishViewModel viewModel = new DishViewModel
            {
                Dish = repository.GetDishById(dishId)
            };
            viewModel.checkBooleans();
            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> EditDish(DishViewModel dishViewModel)
        {
            var user = await userManager.GetUserAsync(HttpContext.User);
            System.Diagnostics.Debug.WriteLine("Dish image: " + dishViewModel.Image);

            if (ModelState.IsValid)
            {
                if(dishViewModel.Image != null)
                {
                    MemoryStream ms = new MemoryStream();
                    dishViewModel.Image.CopyTo(ms);
                    byte[] imageArray = ms.ToArray();

                    dishViewModel.Dish.Image = imageArray;
                }

                dishViewModel.Dish.ChefEmail = user.Email;
                dishViewModel.Dish.DietaryRestrictions = dishViewModel.DietaryInt;
                dishViewModel.Dish.DishCategory = dishViewModel.CategorieInt;

                repository.SaveDish(dishViewModel.Dish);
                TempData["message"] = $"{dishViewModel.Dish.Name} is opgeslagen";
                return RedirectToAction("Dishes");
            } else
            {
                return View(dishViewModel);
            }
        }

        public IActionResult DeleteDish(int dishId)
        {
            Dish deletedDish = repository.deleteDish(dishId);
            if (deletedDish != null) {
                TempData["message"] = $"{deletedDish.Name} is verwijderd";
            }
            return RedirectToAction("Dishes");
        }


    }
}

EM.GUI_Chef/Controllers/WeekplanController.cs
using EM.AppServices;
using EM.Domain;
using EM.DomainServices;
using EM.GUI_Chef.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Linq;
using System.Threading.Tasks;

using EM.Domain.Chef_Entities;

namespace EM.GUI_Chef.Controllers
{
    [Authorize]
    public class WeekplanController : Controller
    {
        private UserManager<IdentityUser> userManager;
        private SignInManager<IdentityUser> signInManager;
        private IChefRepository repository;

        public WeekplanController(UserManager<IdentityUser> userMgr,
            SignInManager<IdentityUser> signInMgr, IChefRepository repo)
        {
            repository = repo;
            userManager = userMgr;
            signInManager = signInMgr;
        }

        public async Task<IActionResult> WeekPlans()
        {
            var user = await userManager.GetUserAsync(HttpContext.User);
            return View(repository.WeekPlans(user.Email));
        }

        public IActionResult CreateWeekplan()
        {
            WeekplanViewModel viewModel = GetWeekplanViewModel();
            SaveWeekplanViewModel(viewModel);

            return View("EditWeekplan", viewModel);
        }

        public async Task<IActionResult> EditWeekplan(int weekplanId)
        {
            var user = await userManager.GetUserAsync(HttpContext.User);
            WeekPlan plan = repository.WeekPlans(user.Email)
                .FirstOrDefault(wp => wp.Id == weekplanId);

            System.Diagnostics.Debug.WriteLine("Logging my current weekplan from EditWeekplan");
            System.Diagnostics.Debug.WriteLine(JsonConvert.SerializeObject(plan, new JsonSerializerSettings()
            {
                PreserveReferencesHandling = PreserveReferencesHandling.Objects,
                Formatting = Formatting.Indented
            }));


            foreach (WeekDay day in plan.WeekDays)
            {
                foreach(Meal meal in day.Meals)
                {
                    if(meal.StarterId != 0) { meal.Starter = repository.GetDishById(meal.StarterId);}
                    if (meal.MainId != 0) { meal.Main = repository.GetDishById(meal.MainId); }
                    if (meal.DessertId != 0) { meal.Dessert = repository.GetDishById(meal.DessertId); }
                }
            }

            WeekplanViewModel viewModel = new WeekplanViewModel
            {
                WeekPlan = plan
            };

            SaveWeekplanViewModel(viewModel);

            return View(viewModel);
        }

        public IActionResult EditWeekday(int dayIndex)
        {
            WeekDay day = GetWeekplanViewModel().WeekPlan.WeekDays.ElementAt(dayIndex);
            WeekdayViewModel viewModel = new WeekdayViewModel
            {
                day = day,
                dayIndex = dayIndex
            };

            System.Diagnostics.Debug.WriteLine("Logging my current weekplan from EditWeekday");
            System.Diagnostics.Debug.WriteLine(JsonConvert.SerializeObject(GetWeekplanViewModel(), new JsonSerializerSettings()
            {
                PreserveReferencesHandling = PreserveReferencesHandling.Objects,
                Formatting = Formatting.Indented
            }));

            return View(viewModel);
        }

        private WeekplanViewModel GetWeekplanViewModel()
        {
            WeekplanViewModel viewModel = HttpContext.Session
                .GetJson<WeekplanViewModel>("WeekplanViewModel");

            if(viewModel == null)
            {
                DateTime today = DateTime.Today;
                int daysUntilMonday = ((int)DayOfWeek.Monday - (int)today.DayOfWeek + 7) % 7;

                DateTime nextMonday;
                if (daysUntilMonday == 0) { nextMonday = today.AddDays(7); }
                else { nextMonday = today.AddDays(daysUntilMonday); }

                WeekPlan newPlan = new WeekPlan()
                {
                    StartDate = nextMonday
                };

                WeekplanViewModel newViewModel = new WeekplanViewModel
                {
                    WeekPlan = newPlan
                };

                newViewModel.initiate();

                viewModel = newViewModel;
            }

            return viewModel;
        }
        private void SaveWeekplanViewModel(WeekplanViewModel viewModel)
        {
            HttpContext.Session.SetJson("WeekplanViewModel", viewModel);
        }
        private void DeleteWeekplanViewModel()
        {
            HttpContext.Session.SetJson("WeekplanViewModel", null);
        }

        public IActionResult CreateMeal(int dayIndex)
        {
            System.Diagnostics.Debug.WriteLine("Logging my current weekplan from CreateMeal");
            System.Diagnostics.Debug.WriteLine(JsonConvert.SerializeObject(GetWeekplanViewModel(), new JsonSerializerSettings()
            {
                PreserveReferencesHandling = PreserveReferencesHandling.Objects,
                Formatting = Formatting.Indented
            }));

            WeekplanViewModel planModel = GetWeekplanViewModel();
            planModel.WeekPlan.WeekDays.ElementAt(dayIndex).Meals.Add(new Meal());

            int mealIndex = planModel.WeekPlan.WeekDays.ElementAt(dayIndex).Meals.Count() - 1;

            MealViewModel viewModel = new MealViewModel()
            {
                Meal = planModel.WeekPlan.WeekDays.ElementAt(dayIndex).Meals.Last(),
                dayIndex = dayIndex,
                mealIndex = mealIndex
            };
            viewModel.initiate();

            SaveWeekplanViewModel(planModel);
            return View("EditMeal", viewModel);
        }

        public IActionResult EditMeal(int dayIndex, int mealIndex)
        {
            WeekplanViewModel planModel = GetWeekplanViewModel();
            MealViewModel viewModel = new MealViewModel()
            {
                Meal = planModel.WeekPlan.WeekDays.ElementAt(dayIndex).Meals.ElementAt(mealIndex),
                dayIndex = dayIndex,
                mealIndex = mealIndex
            };
            viewModel.initiate();

            return View(viewModel);
        }

        public IActionResult DeleteMeal(int dayIndex, int mealIndex)
        {
            WeekplanViewModel planModel = GetWeekplanViewModel();
            Meal toBeRemoved = planModel.WeekPlan.WeekDays
                .ElementAt(dayIndex).Meals.ElementAt(mealIndex);

            planModel.WeekPlan.WeekDays.ElementAt(dayIndex).Meals.Remove(toBeRemoved);
            SaveWeekplanViewModel(planModel);

            WeekDay day = planModel.WeekPlan.WeekDays.ElementAt(dayIndex);
            WeekdayViewModel viewModel = new WeekdayViewModel
            {
                day = day,
                dayIndex = dayIndex
            };

            return View("EditWeekday", viewModel);
        }

        public async Task<IActionResult> SelectStarter(int dayIndex, int mealIndex)
        {
            var user = await userManager.GetUserAsync(HttpContext.User);
            IQueryable<DishViewModel> Dishes = repository
                .Dishes(user.Email).Where(d => d.DishCategory > 3)
                .Select(d => new DishViewModel { Dish = d });

            MealDishViewModel viewModel = new MealDishViewModel()
            {
                Dishes = Dishes,
                dayIndex = dayIndex,
                mealIndex = mealIndex,
                returnAction = "SetStarter",
                dishCategory = "voorgerecht"
            };

            return View("SelectDish", viewModel);
        }
        public async Task<IActionResult> SelectMain(int dayIndex, int mealIndex)
        {
            var user = await userManager.GetUserAsync(HttpContext.User);
            IQueryable<DishViewModel> Dishes = repository
                .Dishes(user.Email).Where(d => 
                d.DishCategory == 2 || d.DishCategory == 3 || d.DishCategory == 7 || d.DishCategory == 6)
                .Select(d => new DishViewModel { Dish = d });

            MealDishViewModel viewModel = new MealDishViewModel()
            {
                Dishes = Dishes,
                dayIndex = dayIndex,
                mealIndex = mealIndex,
                returnAction = "SetMain",
                dishCategory = "hoofdgerecht"
            };

            return View("SelectDish", viewModel);
        }
        public async Task<IActionResult> SelectDessert (int dayIndex, int mealIndex)
        {
            var user = await userManager.GetUserAsync(HttpContext.User);
            IQueryable<DishViewModel> Dishes = repository
                .Dishes(user.Email).Where(d =>
                d.DishCategory == 1 || d.DishCategory == 3 || d.DishCategory == 7 || d.DishCategory == 5)
                .Select(d => new DishViewModel { Dish = d });

            MealDishViewModel viewModel = new MealDishViewModel()
            {
                Dishes = Dishes,
                dayIndex = dayIndex,
                mealIndex = mealIndex,
                returnAction = "SetDessert",
                dishCategory = "nagerecht"
            };

            return View("SelectDish", viewModel);
        }

        public IActionResult SetStarter(int dayIndex, int mealIndex, int dishId)
        {
            Dish Dish = repository.GetDishById(dishId);
            WeekplanViewModel plan = GetWeekplanViewModel();
            plan.WeekPlan.WeekDays.ElementAt(dayIndex).Meals.ElementAt(mealIndex).Starter = Dish;
            plan.WeekPlan.WeekDays.ElementAt(dayIndex).Meals.ElementAt(mealIndex).StarterId = Dish.Id;
            SaveWeekplanViewModel(plan);

            MealViewModel viewModel = new MealViewModel()
            {
                Meal = plan.WeekPlan.WeekDays.ElementAt(dayIndex).Meals.ElementAt(mealIndex),
                dayIndex = dayIndex,
                mealIndex = mealIndex
            };

EM.GUI_Chef/Views/Dashboard/Dishes.cshtml
@model IEnumerable<DishViewModel>


<div class="dishHeader">
    <a class="btn btn-info" asp-action="CreateDish">Gerecht aanmaken</a>
</div>

@if(!Model.Any())
{
    <h1 class="display-4 text-center no-dishes">Geen gerechten gevonden</h1>
}


@foreach (DishViewModel d in Model)
{
    <div class="DishContainer">
        @if (d.Dish.Image == null)
        {<img class="dishImg" src="~/img/NoImageAvailable.png" />}
        else
        { <img class="dishImg" src="data:image/jpg;base64,@Convert.ToBase64String(d.Dish.Image)" />}

        <h6 class="dishName">@d.Dish.Name.ToUpper()</h6>
        <h5 class="dishPrice">&euro;@d.Dish.Price</h5>

        <hr />

        <div class="dishCategories">
            <p><b>Categorieën</b></p>
            <ul>
                @foreach (string s in d.Categories)
                {
                    <li>@s</li>
                }
            </ul>
        </div>

        <div class="dishDiet">
            <p><b>Geschikt voor</b></p>
            <ul>
                @foreach (string s in d.DietaryRepresentation)
                {
                    <li>@s</li>
                }
            </ul>
        </div>

        <div class="options">
            <a asp-action="EditDish" asp-route-dishId="@d.Dish.Id"><i class="material-icons">edit</i></a>
            <a asp-action="DeleteDish" asp-route-dishId="@d.Dish.Id"><i class="material-icons">delete</i></a>
        </div>


    </div>
}

EM.GUI_Chef/Views/Dashboard/EditDish.cshtml
@model DishViewModel
@{ 
    ViewBag.Title = "Gerecht Aanpassen";
}

    <form asp-action="EditDish" enctype="multipart/form-data" method="post">
        <div class="row">
            <div class="col-md-6">
                <input type="hidden" asp-for="Dish.Id" />
                <div class="form-group">
                    <label asp-for="Dish.Name">Naam</label>
                    <div><span asp-validation-for="Dish.Name" class="text-danger"></span></div>
                    <input asp-for="Dish.Name" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="Dish.Description">Beschrijving</label>
                    <div><span asp-validation-for="Dish.Description" class="text-danger"></span></div>
                    <textarea asp-for="Dish.Description" class="form-control"></textarea>
                </div>
                <div class="form-group">
                    <label asp-for="Dish.Price">Prijs</label>
                    <div><span asp-validation-for="Dish.Price" class="text-danger"></span></div>
                    <input asp-for="Dish.Price" class="form-control" />
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Image">Afbeelding</label>
                    <input asp-for="Image" class="form-control-file" accept="image/x-jpg">
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <label><b>Categorieën</b></label>
                        <div class="form-group">
                            <div class="checkbox">
                                <label asp-for="isStarter">
                                    <input asp-for="isStarter" /> Voorgerecht
                                </label>
                            </div>
                            <div class="checkbox">
                                <label asp-for="isMain">
                                    <input asp-for="isMain" /> Hoofdgerecht
                                </label>
                            </div>
                            <div class="checkbox">
                                <label asp-for="isDessert">
                                    <input asp-for="isDessert" /> Nagerecht
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <label><b>Geschikt voor</b></label>
                        <div class="form-group">
                            <div class="checkbox">
                                <label asp-for="salt">
                                    <input asp-for="salt" /> Zoutloos
                                </label>
                            </div>
                            <div class="checkbox">
                                <label asp-for="diabetes">
                                    <input asp-for="diabetes" /> Diabetus
                                </label>
                            </div>
                            <div class="checkbox">
                                <label asp-for="gluten">
                                    <input asp-for="gluten" /> Glutenallergie
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="text-center">
            <button class="btn btn-primary" type="submit">Opslaan</button>
            <a asp-action="Index" class="btn btn-secondary">Annuleren</a>
        </div>
    </form>

EM.GUI_Chef/Views/Dashboard/Index.cshtml
@{
    ViewData["Title"] = "Dashboard";
}

<div class="text-center">
    <h1 class="display-4">Mijn Dashboard</h1>

    <div class="row">
        <div class="col-md-6 chefPadding">
            <div class="chefNavItem">
                <a asp-action="Dishes">
                    <div class="imgContainer">
                        <img src="~/img/DishImage.jpg" />
                    </div>
                    <h4>Mijn Gerechten</h4>
                </a>
            </div>
        </div>

        <div class="col-md-6 chefPadding">
            <div class="chefNavItem">
                <a asp-action="WeekPlans" asp-controller="Weekplan">
                    <div class="imgContainer">
                        <img src="~/img/WeekplanImage.jpg" />
                    </div>
                    <h4>Mijn Weekplannen</h4>
                </a>
            </div>
        </div>
    </div>

</div>